openapi: 3.0.1
info:
  title: api1
  description: API Definition of api1
  version: 1.0.0
servers:
- url: http://localhost:8290/api1
paths:
  /:
    get:
      responses:
        default:
          description: Default response
